# Generated by Django 5.2.8 on 2025-11-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EEGSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='eeg_data/')),
                ('dominant_band', models.CharField(blank=True, max_length=100, null=True)),
                ('inferred_state', models.TextField(blank=True, null=True)),
                ('avg_power', models.FloatField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
