# Generated by Django 5.2.8 on 2025-11-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_userprofile_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
